### ISSUE TITLE
The suggested list of words persists after the search word is deleted.

### ISSUE THREAD

**Issue by farahfarahmand** [Project-Heimdall/home#58] opened 2016-08-01 19:05 UTC
Typed in a word in the Search box and got some suggested words. However, after either deleting the word in the Search box or completing the search, the list of suggested words persists and does not go away.

**Comment by camelspeed** [comment] 2016-08-02 12:27
duplicate of Project-Heimdall/heimdall-uiapp#124

**Closed by camelspeed** 2016-08-02 12:27 UTC
Labels: bug, duplicate
